"""
api/main.py

FastAPI backend for the Brain Tumor Detection System.


How to run:
    cd brain-tumor-project
    uvicorn api.main:app --reload --port 8000

Endpoints:
    GET  /          → API info
    GET  /health    → Health check
    POST /predict   → Upload MRI → get diagnosis
    GET  /docs      → Interactive API docs (auto-generated by FastAPI)
"""

import sys
import os

# ─── PATH SETUP ──────
# Add project root to path so we can import from model/
sys.path.append(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
)

from fastapi import FastAPI, File, UploadFile, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from PIL import Image
import io
import torch

from model.predictor import load_model, predict, CLASS_NAMES

# ─── APP SETUP ────────────

app = FastAPI(
    title       = "Brain Tumor Detection API",
    description = "Upload a brain MRI scan and get AI-powered tumor classification",
    version     = "1.0.0",
    docs_url    = "/docs",   # Interactive docs at http://localhost:8000/docs
)

# ─── CORS ─────────
# Allows the React frontend (localhost:5173) to talk to this API (localhost:8000)


app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],        
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ─── LOAD MODEL AT STARTUP ──────────

model = None

@app.on_event("startup")
async def startup_event():
    global model
    print("\n🧠 Brain Tumor Detection API starting...")
    print("📦 Loading EfficientNet model...")
    model = load_model()
    print("🚀 API ready!\n")


# ─── ENDPOINTS ──────────
@app.get("/")
def root():
    """API information endpoint."""
    return {
        "name":        "Brain Tumor Detection API",
        "version":     "1.0.0",
        "status":      "running",
        "model":       "EfficientNet-B0",
        "classes":     CLASS_NAMES,
        "docs":        "http://localhost:8000/docs",
        "disclaimer":  "Research prototype only. Not for clinical use."
    }


@app.get("/health")
def health_check():
    """
    Health check endpoint.
    Used to verify the API and model are both running correctly.
    """
    return {
        "status":       "healthy",
        "model_loaded": model is not None,
        "device":       str(torch.device("cuda" if torch.cuda.is_available() else "cpu")),
        "classes":      CLASS_NAMES
    }


@app.post("/predict")
async def predict_tumor(file: UploadFile = File(...)):
    """
    Main prediction endpoint.

    - Accepts: Brain MRI image (JPG or PNG)
    - Returns: Tumor classification with confidence scores

    Example Response:
    {
        "filename": "mri_scan.jpg",
        "predicted_class": "glioma",
        "display_name": "Glioma",
        "confidence": 92.15,
        "probabilities": {
            "glioma": 92.15,
            "meningioma": 2.60,
            "notumor": 5.10,
            "pituitary": 0.15
        },
        "info": {
            "description": "A tumor that starts in the glial cells...",
            "severity": "High",
            "color": "#ef4444"
        }
    }
    """

    # ── Validate file type ────────
    allowed_types = ["image/jpeg", "image/png", "image/jpg"]
    if file.content_type not in allowed_types:
        raise HTTPException(
            status_code = 400,
            detail      = f"Invalid file type '{file.content_type}'. Please upload JPG or PNG."
        )

    # ── Read image ───────
    try:
        contents = await file.read()
        image    = Image.open(io.BytesIO(contents))
    except Exception as e:
        raise HTTPException(
            status_code = 400,
            detail      = f"Could not read image: {str(e)}"
        )

    # ── Run prediction ────────────────────────────────────────────────────────
    try:
        result = predict(image, model)
    except Exception as e:
        raise HTTPException(
            status_code = 500,
            detail      = f"Prediction failed: {str(e)}"
        )

    # ── Return result ─────────────────────────────────────────────────────────
    return JSONResponse(content={
        "filename":        file.filename,
        "predicted_class": result["predicted_class"],
        "display_name":    result["display_name"],
        "confidence":      result["confidence"],
        "probabilities":   result["probabilities"],
        "info":            result["info"]
    })
